const js = require("@eslint/js");
const tsParser = require("@typescript-eslint/parser");
const tsPlugin = require("@typescript-eslint/eslint-plugin");
const importPlugin = require("eslint-plugin-import");

module.exports = [
  js.configs.recommended,
  {
    ignores: ["node_modules/", "dist/", "build/", "*.min.js"],
  },
  {
    files: ["src/**/*.ts"],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 2021,
        sourceType: "module",
      },
      globals: {
        // Tampermonkey/Greasemonkey globals
        GM_xmlhttpRequest: "readonly",
        GM_getValue: "readonly",
        GM_setValue: "readonly",
        GM_addStyle: "readonly",
        GM_info: "readonly",
        GM_registerMenuCommand: "readonly",
        // Browser globals
        console: "readonly",
        document: "readonly",
        window: "readonly",
        navigator: "readonly",
        alert: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        getComputedStyle: "readonly",
        MutationObserver: "readonly",
        sessionStorage: "readonly",
        FileReader: "readonly",
        Blob: "readonly",
        URL: "readonly",
        CustomEvent: "readonly",
        Event: "readonly",
        AbortController: "readonly",
        fetch: "readonly",
        URLSearchParams: "readonly",
        CSS: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        HTMLInputElement: "readonly",
      },
    },
    plugins: {
      "@typescript-eslint": tsPlugin,
      import: importPlugin,
    },
    rules: {
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrors: "none",
        },
      ],
      "no-undef": "off",
      "no-console": "off",
      "no-debugger": "error",
      eqeqeq: "error",
      curly: "error",
      "no-var": "error",
      "prefer-const": "error",
      "no-implicit-coercion": "error",
      "no-constant-condition": "error",
      "no-unreachable": "error",
      "no-dupe-args": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "valid-typeof": "error",
      "no-func-assign": "error",
      "no-unused-expressions": "error",
      "no-self-assign": "error",
      "no-sparse-arrays": "error",
      "no-unexpected-multiline": "error",
      "no-unsafe-negation": "error",
      "use-isnan": "error",
      "no-useless-escape": "error",
      // Import/Export Rules - Make these strict to fail the build
      "import/no-unresolved": "error",
      "import/named": "error",
      "import/default": "error",
      "import/namespace": "error",
      "import/no-absolute-path": "error",
      "import/no-dynamic-require": "error",
      "import/no-webpack-loader-syntax": "error",
      "import/no-self-import": "error",
      "import/no-useless-path-segments": "error",
      "import/export": "error",
      "import/no-named-as-default": "error",
      "import/no-named-as-default-member": "error",
      "import/no-extraneous-dependencies": "error",
      "import/no-mutable-exports": "error",
      "import/prefer-default-export": "off",
      "import/first": "error",
      "import/no-duplicates": "error",
      "import/order": "error",
      "import/newline-after-import": "error",
      "import/group-exports": "off",
      "import/extensions": ["error", "ignorePackages", {
        js: "never",
        ts: "never",
      }],
    },
    settings: {
      "import/resolver": {
        node: {
          extensions: [".ts", ".js"],
        },
      },
    },
  },
];
